name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  goTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif

#    - name: Upload result to GitHub Code Scanning
#      uses: github/codeql-action/upload-sarif@v2
#      with:
#        sarif_file: snyk.sarif

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Test
      run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      env:
        ENVIRONMENT: ci
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        OAUTH_CALLBACK_ROOT: ${{ secrets.OAUTH_CALLBACK_ROOT }}
        COGNITO_CALLBACK_URLS: https://github.com

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
